language: php

php:
  - "5.3"
  - "5.4"
  - "5.5"
  - "5.6"
  - "hhvm"

install:
  - composer install --dev
  - composer show -i

before_script:

script:
  - ./vendor/bin/php-cs-fixer fix -v --dry-run --fixers=-psr0,psr4 src;
  - ./vendor/bin/php-cs-fixer fix -v --dry-run --fixers=-psr0,psr4 tests;
  - cd tests ; ../vendor/bin/phpunit

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.6
    - php: hhvm
